// import { useState } from "react";

export async function generateMetadata() {
  return {
    title: "Neflix - Movies",
    description: "Generated by create next app",
    keywords: "movies, netflix",
  };
}
export default async function MoviesPage() {
  // const [counter, setCounter] = useState(0);

  return (
    <div>
      <h1>This is a server side rendered page</h1>
      {/* <br /> */}
      {/* <p>Counter (persists during SPA navigation): {counter}</p> */}
      {/* <button onClick={() => setCounter(c => c + 1)}>+1</button> */}
    </div>
  );
}
